Improved sudo handling
The sudo wrapper will now not require the .cipassword file to
be present for sudo operations (falling back to sudoers handling
or prompting for password) - but will ensure secure file protection
if the file indeed is there.

diff --git a/ci_fuel_opnfv/tools/sudo b/ci_fuel_opnfv/tools/sudo
--- a/ci_fuel_opnfv/tools/sudo
+++ b/ci_fuel_opnfv/tools/sudo
@@ -8,6 +8,35 @@
 # which accompanies this distribution, and is available at
 # http://www.apache.org/licenses/LICENSE-2.0
 ##############################################################################
+
+############################################################################
+# BEGIN of password storage verification
+#
+function verify_pwstore() {
+    local PWFILE
+    PWFILE=$HOME/.cipassword
+
+    if [ $(find $PWFILE ! -perm /g+r ! -perm /o+r | wc -l) -eq 0 ]; then
+        echo "Error: $PWFILE is readable by group and/or owner." >&2
+        echo "Make sure to: chmod g-rwx,o-rwx $PWFILE" >&2
+        exit 1
+    fi
+}
+
+# END of password storage verification
+############################################################################
+
+
+
+
+
 umask 0002
 PWFILE=$HOME/.cipassword
-cat $PWFILE | /usr/bin/sudo -S $@
+if [ -f $PWFILE ]; then
+    verify_pwstore
+    echo "sudo will run (with pwfile): $@" >&2
+    cat $PWFILE | /usr/bin/sudo -S $@
+else
+    echo "sudo will run (without pwfile): $@" >&2
+    /usr/bin/sudo $@
+fi
